### ISSUE TITLE
有几个疑问

### ISSUE THREAD

**Issue by keyescgm** [akshay2211/MusicWave#2]
我找其他方式实现的，和你的类似；
有几个问题请教下
1、SurfaceView或者你的WaveView  图层下如何添加一个表格，横坐标：时间/纵坐标：频率 
2、SurfaceView或者你的WaveView  如何从屏幕左端开始绘制
3、拖动问题，你draw的这些线都划过屏幕之后就在缓存中把...能拖动显示吗

**Comment by akshay2211** [comment]
Hello @keyescgm 
I guess u are trying to draw wave from left to right
sorry but WaveView is not meant for that, but you can take reference 
from this snippet from WaveView.
`for (int i = 0; i < mBytes.length - 1; i++) {
            mPoints[i * size] = mRect.width() * i / (mBytes.length - 1);
            mPoints[i * size + 1] = mRect.height() / 2 + ((byte) (mBytes[i] + 128)) * (mRect.height() / 2) / 128;
            mPoints[i * size + 2] = mRect.width() * (i + 1) / (mBytes.length - 1);
            mPoints[i * size + 3] = mRect.height() / 2 + ((byte) (mBytes[i + 1] + 128)) * (mRect.height() / 2) / 128;
        }`


Try to store and display the byte data accordingly and instead of mBytes.length use the time variable.
I guess this might resolve your issue.
